import type { Quelle } from '@/types';

export const KRYPTO_QUELLEN: Quelle[] = [
  {
    id: 'nist-fips-197',
    typ: 'standard',
    titel: 'Advanced Encryption Standard (AES)',
    organisation: 'NIST',
    nummer: 'FIPS 197',
    jahr: 2001,
    url: 'https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197-upd1.pdf',
  },
  {
    id: 'nist-fips-180-4',
    typ: 'standard',
    titel: 'Secure Hash Standard (SHS)',
    organisation: 'NIST',
    nummer: 'FIPS 180-4',
    jahr: 2015,
    url: 'https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf',
  },
  {
    id: 'rfc-8446',
    typ: 'rfc',
    titel: 'The Transport Layer Security (TLS) Protocol Version 1.3',
    nummer: 8446,
    jahr: 2018,
    url: 'https://www.rfc-editor.org/rfc/rfc8446',
  },
  {
    id: 'rfc-6749',
    typ: 'rfc',
    titel: 'The OAuth 2.0 Authorization Framework',
    nummer: 6749,
    jahr: 2012,
    url: 'https://www.rfc-editor.org/rfc/rfc6749',
  },
  {
    id: 'rfc-2104',
    typ: 'rfc',
    titel: 'HMAC: Keyed-Hashing for Message Authentication',
    nummer: 2104,
    jahr: 1997,
    url: 'https://www.rfc-editor.org/rfc/rfc2104',
  },
  {
    id: 'diffie1976-newdirections',
    typ: 'paper',
    autoren: ['Whitfield Diffie', 'Martin E. Hellman'],
    titel: 'New Directions in Cryptography',
    jahr: 1976,
    venue: 'IEEE Transactions on Information Theory',
  },
  {
    id: 'rivest1978-rsa',
    typ: 'paper',
    autoren: ['Ron Rivest', 'Adi Shamir', 'Leonard Adleman'],
    titel: 'A Method for Obtaining Digital Signatures and Public-Key Cryptosystems',
    jahr: 1978,
    venue: 'Communications of the ACM',
    doi: '10.1145/359340.359342',
  },
  {
    id: 'katz-lindell-2021',
    typ: 'buch',
    autoren: ['Jonathan Katz', 'Yehuda Lindell'],
    titel: 'Introduction to Modern Cryptography',
    jahr: 2021,
    verlag: 'CRC Press',
    isbn: '9780815354369',
  },
  {
    id: 'nist-fips-186-5',
    typ: 'standard',
    titel: 'Digital Signature Standard (DSS)',
    organisation: 'NIST',
    nummer: 'FIPS 186-5',
    jahr: 2023,
    url: 'https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf',
  },
  {
    id: 'nist-fips-203',
    typ: 'standard',
    titel: 'Module-Lattice-Based Key-Encapsulation Mechanism Standard (ML-KEM)',
    organisation: 'NIST',
    nummer: 'FIPS 203',
    jahr: 2024,
    url: 'https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.pdf',
  },
  {
    id: 'rfc-9106',
    typ: 'rfc',
    titel: 'Argon2 Memory-Hard Function for Password Hashing and Proof-of-Work Applications',
    nummer: 9106,
    jahr: 2021,
    url: 'https://www.rfc-editor.org/rfc/rfc9106',
  },
  {
    id: 'nist-sp-800-38d',
    typ: 'standard',
    titel: 'Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM) and GMAC',
    organisation: 'NIST',
    nummer: 'SP 800-38D',
    jahr: 2007,
    url: 'https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf',
  },
];

export function kryptoQuelleFinden(id: string): Quelle | undefined {
  return KRYPTO_QUELLEN.find((q) => q.id === id);
}
